language: android

android:
  components:
    - platform-tools
    - tools
    - extra
    - add-on
before_script:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"
  - echo no | android --silent create avd --force -n stage_emulator -t android-29
  - emulator -list-avds
  - emulator -avd stage_emulator -no-audio -no-window &
  - export ANDROID_SDK_HOME=$ANDROID_HOME
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - echo "fé"
  - curl -s "https://get.sdkman.io" | bash && source "/home/travis/.sdkman/bin/sdkman-init.sh" && sdk install gradle 6.5.1
  - ./gradlew connectedCheck
cache:
  directories:
    - $HOME/.gradle

jobs:
  include:
    - stage: test
      if: branch = master
      script: echo "é master"
